login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('signin', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('success', views.success, name='success'),
    path('logout', views.logout_user, name='logout'),
]

room/urls.py
from django.urls import path

from . import views

app_name = 'room'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('question', views.your_question, name='question'),
    path('<int:question_id>/question_deleted', views.delete_question, name='delete_question'),
    path('<int:answer_id>/answer_deleted', views.delete_answer, name='delete_answer'),
    path('topquestion', views.top_questions, name='top_question'),
    path('latestquestion', views.latest_questions, name='latest_question'),
    path('answers', views.your_answer, name='answer'),
    path('login', views.login_user, name='login'),
    path('question_updated', views.update_question, name='update_question'),
    path('<int:question_id>/answer_updated', views.update_answer, name='update_answer'),
    path('<int:question_id>/question', views.to_question, name='to_question'),
    path('<int:answer_id>/to_edit', views.to_edit, name='to_edit'),
    path('<int:answer_id>/answer_edited', views.edit_answer, name='edit_answer'),
    path('<int:answer_id>/answer_liked', views.like, name='like'),
]

studyROOM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('login.urls')),
    path('', include('room.urls')),
    path('admin/', admin.site.urls),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.contrib.auth import authenticate
from django.db import IntegrityError
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.http import HttpResponse


def index(request):
    return render(request, 'login/index.html')


def login(request):
    return render(request, 'login/login.html')


def signup(request):
    return render(request, 'login/signup.html')


def success(request):
    try:
        user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'],
                                        email=request.POST['email'], first_name=request.POST['firstname'],
                                        last_name=request.POST['lastname'])
        user.save()
        return render(request, 'login/signupsucess.html')
    except IntegrityError:
        return render(request, 'login/signup.html', {'error': True})


def logout_user(request):
    logout(request)
    return render(request, 'login/index.html')

login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>studyROOM-Login</title>
    <link rel="stylesheet" href="{% static 'login/index.css' %}">
</head>
<body>
    <div class="heading_1">Hi!, Welcome to</div>
    <div class="heading_2">study<span class="bold">ROOM</span></div>
    <div class="description">            <p>The study room gives you a collaborative environment to learn. You can post your questions, and others can answer your questions as well as you also can answer other questions. If you want to improve this application or contribute to this application, you can fork from my github repository. <a href="https://github.com/josiahprathaban/studyROOM" target="_blank">https://github.com /josiahprathaban /studyROOM.</a> Make use of it. Have fun!</p></div>
    <div class="buttons">
        <span class="button_dis">already have an account</span>
        <span class="button_dis">create an new account</span>
        <a href="{% url 'login:login' %}"><span class="button">LogIn</span></a>
        <a href="{% url 'login:signup' %}"><span class="button">SignUp</span></a>
    </div>
</body>
</html>

login/templates/login/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>studyROOM-SignIn</title>
    <link rel="stylesheet" href="{% static 'login/login.css' %}">
</head>
<body>
    <div class="heading_2">study<span class="bold">ROOM</span></div>
    <div class="heading_1">login </div>
    <form action="{% url 'room:login'%}" method="post">
        {% csrf_token %}
        <label>Username or e-mail</label><br>
        <input type="text" name="username" placeholder="username or e-mail" required><br>
        <label>Password</label><br>
        <input type="password" name="password" placeholder="password" required><br>
        {% if error %}
            <label style="color: #a34040"><i>Invalid username or password!</i></label><br>
        {% endif %}
        <input type="submit" name="Login" value="Login">
    </form>
    <a href="{% url 'login:signup' %}">don't have an account, create new?</a>

</body>
</html>

login/templates/login/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>studyROOM-SignUp</title>
    <link rel="stylesheet" href="{% static 'login/signup.css' %}">
</head>
<body>
    <div class="heading_2">study<span class="bold">ROOM</span></div>
    <div class="heading_1">signup </div>
    <form action="{% url 'login:success'%}" method="post">
        {% csrf_token %}
        <label>First name</label><br>
        <input type="text" name="firstname" placeholder="firstname" required><br>
        <label>Last name</label><br>
        <input type="text" name="lastname" placeholder="lastname" required><br>
        <label>Username</label><br>
        <input type="text" name="username" placeholder="username" required><br>
        <label>E-mail</label><br>
        <input type="email" name="email" placeholder="e-mail" required><br>
        <label>Password</label><br>
        <input type="password" name="password" placeholder="password" required><br>
        {% if error %}
            <label style="color: #a34040"><i>The username is already taken, try different!</i></label><br>
        {% endif %}
        <input type="submit" name="Login" value="Signup">
    </form>
    <a href="{% url 'login:login' %}">already have an account, login now?</a>
</body>
</html>

login/templates/login/signupsucess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Title</title>
</head>
<body>
Successfully sign up
<a href="{% url 'login:login' %}">click here to login</a>
</body>
</html>