login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.index, name='index'),
    path('signin', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('success', views.success, name='success'),
    path('logout', views.logout_user, name='logout'),
]

room/urls.py
from django.urls import path

from . import views

app_name = 'room'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('question', views.your_question, name='question'),
    path('<int:question_id>/question_deleted', views.delete_question, name='delete_question'),
    path('<int:answer_id>/answer_deleted', views.delete_answer, name='delete_answer'),
    path('topquestion', views.top_questions, name='top_question'),
    path('latestquestion', views.latest_questions, name='latest_question'),
    path('answers', views.your_answer, name='answer'),
    path('login', views.login_user, name='login'),
    path('question_updated', views.update_question, name='update_question'),
    path('<int:question_id>/answer_updated', views.update_answer, name='update_answer'),
    path('<int:question_id>/question', views.to_question, name='to_question'),
    path('<int:answer_id>/to_edit', views.to_edit, name='to_edit'),
    path('<int:answer_id>/answer_edited', views.edit_answer, name='edit_answer'),
    path('<int:answer_id>/answer_liked', views.like, name='like'),
]

studyROOM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('login/', include('login.urls')),
    path('', include('room.urls')),
    path('admin/', admin.site.urls),
]

room/models.py
from django.contrib.auth.models import User
from django.db import models


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=10000)
    key_words = models.CharField(max_length=1000)
    pub_date = models.DateTimeField('date published')
    ans_count = models.IntegerField(default=0)


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=10000)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')

    def top_answers(self):
        return self.objects.order_by('-votes')[:5]

room/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.core.mail import send_mail
from room.models import Question, Answer


def login_user(request):
    user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect('room:index')
    else:
        return render(request, 'login/login.html', {'error': True})


def index(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        latest_question_list = Question.objects.order_by('-pub_date')[:5]
        top_question_list = Question.objects.order_by('-ans_count')[:5]
        context = {
            'user': request.user,
            'latest_question': latest_question_list,
            'top_question': top_question_list,
        }
        return render(request, 'room/index.html', context)


def update_question(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        question = Question(user=request.user, question_text=request.POST['question'], key_words=request.POST['key'],
                            pub_date=timezone.now())
        question.save()
        user_mail = User.objects.exclude(email=request.user.email).values_list("email", flat=True)
        send_mail(
        'studyROOM Notifications',
        str(request.user)+' posted a new Question in studyROOM just now. \nIf you can, just give him an answer : http://josiah.pythonanywhere.com/'+str(question.id)+'/question',
        'josiah.prathaban@gmail.com',
        user_mail,
        fail_silently=False,)
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def update_answer(request, question_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        answer = Answer(user=request.user, question_id=question_id, answer_text=request.POST['answer'],
                        pub_date=timezone.now())
        question = Question.objects.get(pk=question_id)
        question.ans_count = question.ans_count + 1
        question.save()
        answer.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def search(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        s1 = Question.objects.filter(key_words__contains=request.POST['search'])
        s2 = Question.objects.filter(question_text__contains=request.POST['search'])
        search_list = s1.union(s2)
        context = {
            'user': request.user,
            'search_question': search_list,
            'key': request.POST['search'],
        }
        return render(request, 'room/search.html', context)


def like(request, answer_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        answer = Answer.objects.get(pk=answer_id)
        answer.votes = answer.votes + 1
        answer.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def your_question(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        question_list = Question.objects.filter(user=request.user)
        context = {
            'user': request.user,
            'question_list': question_list,
        }
        return render(request, 'room/your_questions.html', context)


def your_answer(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        answer_list = Answer.objects.filter(user=request.user)
        context = {
            'user': request.user,
            'answer_list': answer_list,
        }
        return render(request, 'room/your_answers.html', context)


def latest_questions(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        latest_question_list = Question.objects.order_by('-pub_date')
        context = {
            'user': request.user,
            'question_list': latest_question_list,
        }
        return render(request, 'room/latest_questions.html', context)


def top_questions(request):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        top_question_list = Question.objects.order_by('-ans_count')
        context = {
            'user': request.user,
            'question_list': top_question_list,
        }
        return render(request, 'room/top_questions.html', context)


def delete_question(request, question_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        question = Question.objects.get(pk=question_id)
        question.delete()
        return redirect('room:question')


def delete_answer(request, answer_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        answer = Answer.objects.get(pk=answer_id)
        answer.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def to_question(request, question_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        question = Question.objects.get(pk=question_id)
        context = {
            'user': request.user,
            'question': question,
        }
        return render(request, 'room/question.html', context)


def to_edit(request, answer_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        answer = Answer.objects.get(pk=answer_id)
        context = {
            'user': request.user,
            'answer': answer,
            'edit': True,
            'question': answer.question,
        }
        return render(request, 'room/question.html', context)


def edit_answer(request, answer_id):
    if request.user.is_anonymous:
        return redirect('login:index')
    else:
        answer = Answer.objects.get(pk=answer_id)
        answer.answer_text = request.POST['answer']
        answer.pub_date = timezone.now()
        answer.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

room/templates/room/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    {% load static %}
    <meta http-equiv="refresh" content="300">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>studyROOM-Home</title>
    <link rel="stylesheet" href="{% static 'room/index.css' %}">
</head>
<body>
    <div class="nav">
        <a href="{% url 'room:index' %}">
            <span class="left">
                <span class="heading_2">study<span class="bold">ROOM</span></span><br>
                <span class="heading_1">a collaborative environment</span>
            </span>
        </a>
        <span class="right">
            <form action="{% url 'room:search' %}" method="post">{% csrf_token %}
                <input type="search" name="search" placeholder="Search for a Question" required>
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
        </span>
    </div>
    <div class="contents" id="top">
        <div class="main-content">
            <div class="new-question">
                <form action="{% url 'room:update_question' %}" method="post">{% csrf_token %}
                    <div class="head_1">Post a new Question</div>
                    <div class="head_2">ask what ever you want</div>
                    <textarea class="ques" name="question" required></textarea>
                    <textarea class="key" placeholder="Enter Key words using #" name="key" required></textarea>
                    <input type="submit" value="Post">
                    <input type="reset" value="Cancel">
                </form>
            </div>
            <hr><br>
            <div class="latest-question">
                <div class="head_1"><a href="{% url 'room:latest_question' %}">Latest Questions</a></div><br>
                {% if latest_question %}
                    {% for question in latest_question %}
                        <div class="question_">
                            <div class="user">{{ question.user.username }}{% if question.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ question.pub_date|timesince }} ago</span></div>
                            <div class="_question"><a href="{% url 'room:to_question' question.id %}">{{ question.question_text}}</a></div>
                            {% for answer in question.answer_set.all|slice:":5" %}
                                <div class="answer_">
                                    <div class="user">{{ answer.user.username }}{% if answer.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ answer.pub_date|timesince }} ago</span></div>
                                    <div class="answer">{{ answer.answer_text}}</div>
                                    <div class="edit">{% if answer.user.username == user.username %}
                                        <a href="{% url 'room:to_edit' answer.id %}">edit</a> | <a href="{% url 'room:delete_answer' answer.id%}">delete</a>
                                    {% endif %}</div>
                                <span class="like">{{ answer.votes }} votes <a href="{% url 'room:like' answer.id %}" class="like">| <i class="fas fa-fist-raised"></i></a></span>
                                <div></div>
                                </div>

                                {% empty %}
                                {% if question.user.username != user.username %}
                                <br>
                                <i><b>be the first to answer this question</b></i>
                                {% endif %}
                            {% endfor %}
                            <div class="new-answer"><br>
                                <form action="{% url 'room:update_answer' question.id %}" method="post">{% csrf_token %}
                                    <div class="head_2">Post your answer</div>
                                    <textarea class="post-ans" placeholder="Post your answer for this question" name="answer" required></textarea>
                                    <input type="submit" value="Post">
                                    <input type="reset" value="Cancel">
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
            <hr><br>
            <div class="top-question">
                <div class="head_1"><a href="{% url 'room:top_question' %}">Top Questions</a></div><br>
                {% if top_question %}
                    {% for question in top_question %}
                        <div class="question_">
                            <div class="user">{{ question.user.username }}{% if question.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ question.pub_date|timesince }} ago</span></div>
                            <div class="_question"><a href="{% url 'room:to_question' question.id %}">{{ question.question_text}}</a></div>
                            {% for answer in question.answer_set.all|slice:":5" %}
                                <div class="answer_">
                                    <div class="user">{{ answer.user.username }}{% if answer.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ answer.pub_date|timesince }} ago</span></div>
                                    <div class="answer">{{ answer.answer_text}}</div>
                                    <div class="edit">{% if answer.user.username == user.username %}
                                        <a href="{% url 'room:to_edit' answer.id %}">edit</a> | <a href="{% url 'room:delete_answer' answer.id%}">delete</a>
                                    {% endif %}</div>
                                <span class="like">{{ answer.votes }} votes <a href="{% url 'room:like' answer.id %}" class="like">| <i class="fas fa-fist-raised"></i></a></span>
                                <div></div>
                                </div>

                                {% empty %}
                                {% if question.user.username != user.username %}
                                <br>
                                <i><b>be the first to answer this question</b></i>
                                {% endif %}
                            {% endfor %}
                            <div class="new-answer"><br>
                                <form action="{% url 'room:update_answer' question.id %}" method="post">{% csrf_token %}
                                    <div class="head_2">Post your answer</div>
                                    <textarea class="post-ans" placeholder="Post your answer for this question" name="answer" required></textarea>
                                    <input type="submit" value="Post">
                                    <input type="reset" value="Cancel">
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="side-bar">
            <div class="profile">
                <div class="profile-pic"><i class="fas fa-user-circle"></i></div>
                <div class="profile-name">{{ user.get_full_name }}</div>
                <div class="profile-email">{{ user.email }}</div>
                <div class="profile-dis">Student at University of Kelaniya</div>
                <div class="profile-nav">
                    <nav><b>-- Your Posts --</b></nav>
                    <nav>> <a href="{% url 'room:question' %}">Questions</a></nav>
                    <nav>> <a href="{% url 'room:answer' %}">Answers&nbsp;&nbsp;</a></nav><br>
                    <nav>Settings | <a href="{% url 'login:logout' %}">{% csrf_token %}logout</a></nav><br>
                </div>

            </div>
            <p>The study room gives you a collaborative environment to learn. You can post your questions, and others can answer your questions as well as you also can answer other questions. If you want to improve this application or contribute to this application, you can fork from my github repository. <a href="https://github.com/josiahprathaban/studyROOM" target="_blank">https://github.com /josiahprathaban /studyROOM.</a> Make use of it. Have fun!</p>
            <hr>Powered by<br>
            <unknown>UNKNOWN</unknown><inc> Inc.</inc>
            <br><br><p><b>if you like this application please give a star in my git repository: </b><br> <a href="https://github.com/josiahprathaban/studyROOM" target="_blank">https://github.com /josiahprathaban /studyROOM</a></p>
            <!--<img src="{% static 'room/unknown.svg' %}" width="180px">-->
        </div>
    </div>
    <a href="#top"><div class="up">^<br>up</div></a>
    <div class="footer">
        <span class="head_2">Contact us</span> |
        <a href="https://www.linkedin.com/in/josiah-prathaban/" target="_blank"><i class="fab fa-linkedin"></i></a>  |
        <a href="https://github.com/josiahprathaban" target="_blank"><i class="fab fa-github-square"></i></a>  |
        <a href="https://www.facebook.com/josiah.prathaban" target="_blank"><i class="fab fa-facebook-square"></i></a>  |
        <a href="https://www.blogger.com/profile/14730380695491700190" target="_blank"><i class="fab fa-blogger"></i></a>  |
        <i class="fab fa-whatsapp"></i> <span class="head_2">+94 76 6641 296</span>
    </div>
</body>
</html>

room/templates/room/latest_questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>studyROOM-Questions</title>
    <link rel="stylesheet" href="{% static 'room/index.css' %}">
</head>
<body>
    <div class="nav">
        <a href="{% url 'room:index' %}">
            <span class="left">
                <span class="heading_2">study<span class="bold">ROOM</span></span><br>
                <span class="heading_1">a collaborative environment</span>
            </span>
        </a>
        <span class="right">
            <form action="{% url 'room:search' %}" method="post">{% csrf_token %}
                <input type="search" name="search" placeholder="Search for a Question" required>
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
        </span>
    </div>
    <div class="contents" id="top">
        <div class="main-content">
            <div class="latest-question">
                <div class="head_1">Latest Questions</div><br>
                {% if question_list %}
                    {% for question in question_list %}
                        <div class="question_">
                            <div class="user">{{ question.user.username }}{% if question.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ question.pub_date|timesince }} ago</span></div>
                            <div class="_question"><a href="{% url 'room:to_question' question.id %}">{{ question.question_text}}</a></div>
                            {% for answer in question.answer_set.all|slice:":5" %}
                                <div class="answer_">
                                    <div class="user">{{ answer.user.username }}{% if answer.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ answer.pub_date|timesince }} ago</span></div>
                                    <div class="answer">{{ answer.answer_text}}</div>
                                    <div class="edit">{% if answer.user.username == user.username %}
                                        <a href="{% url 'room:to_edit' answer.id %}">edit</a> | <a href="{% url 'room:delete_answer' answer.id%}">delete</a>
                                    {% endif %}</div>
                                <span class="like">{{ answer.votes }} votes <a href="{% url 'room:like' answer.id %}" class="like">| <i class="fas fa-fist-raised"></i></a></span>
                                <div></div>
                                </div>

                                {% empty %}
                                {% if question.user.username != user.username %}
                                <br>
                                <i><b>be the first to answer this question</b></i>
                                {% endif %}
                            {% endfor %}
                            <div class="new-answer"><br>
                                <form action="{% url 'room:update_answer' question.id %}" method="post">{% csrf_token %}
                                    <div class="head_2">Post your answer</div>
                                    <textarea class="post-ans" placeholder="Post your answer for this question" name="answer" required></textarea>
                                    <input type="submit" value="Post">
                                    <input type="reset" value="Cancel">
                                </form>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="side-bar">
            <div class="profile">
                <div class="profile-pic"><i class="fas fa-user-circle"></i></div>
                <div class="profile-name">{{ user.get_full_name }}</div>
                <div class="profile-email">{{ user.email }}</div>
                <div class="profile-dis">Student at University of Kelaniya</div>
                <div class="profile-nav">
                    <nav><b>-- Your Posts --</b></nav>
                    <nav>> <a href="{% url 'room:question' %}">Questions</a></nav>
                    <nav>> <a href="{% url 'room:answer' %}">Answers&nbsp;&nbsp;</a></nav><br>
                    <nav>Settings | <a href="{% url 'login:logout' %}">{% csrf_token %}logout</a></nav><br>
                </div>

            </div>
            <p>The study room gives you a collaborative environment to learn. You can post your questions, and others can answer your questions as well as you also can answer other questions. If you want to improve this application or contribute to this application, you can fork from my github repository. <a href="https://github.com/josiahprathaban/studyROOM" target="_blank">https://github.com /josiahprathaban /studyROOM.</a> Make use of it. Have fun!</p>            <hr>Powered by<br>
            <unknown>UNKNOWN</unknown><inc> Inc.</inc>
            <!--<img src="{% static 'room/unknown.svg' %}" width="180px">-->
        </div>
    </div>
    <a href="#top"><div class="up">^<br>up</div></a>
    <div class="footer">
        <span class="head_2">Contact us</span> |
        <a href="https://www.linkedin.com/in/josiah-prathaban/" target="_blank"><i class="fab fa-linkedin"></i></a>  |
        <a href="https://github.com/josiahprathaban" target="_blank"><i class="fab fa-github-square"></i></a>  |
        <a href="https://www.facebook.com/josiah.prathaban" target="_blank"><i class="fab fa-facebook-square"></i></a>  |
        <a href="https://www.blogger.com/profile/14730380695491700190" target="_blank"><i class="fab fa-blogger"></i></a>  |
        <i class="fab fa-whatsapp"></i> <span class="head_2">+94 76 6641 296</span>
    </div>
</body>
</html>

room/templates/room/your_questions.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>studyROOM-Questions</title>
    <link rel="stylesheet" href="{% static 'room/index.css' %}">
</head>
<body>
    <div class="nav">
        <a href="{% url 'room:index' %}">
            <span class="left">
                <span class="heading_2">study<span class="bold">ROOM</span></span><br>
                <span class="heading_1">a collaborative environment</span>
            </span>
        </a>
        <span class="right">
            <form action="{% url 'room:search' %}" method="post">{% csrf_token %}
                <input type="search" name="search" placeholder="Search for a Question" required>
                <button type="submit"><i class="fas fa-search"></i></button>
            </form>
        </span>
    </div>
    <div class="contents" id="top">
        <div class="main-content">
            <div class="new-question">
                <form action="{% url 'room:update_question' %}" method="post">{% csrf_token %}
                    <div class="head_1">Post a new Question</div>
                    <div class="head_2">ask what ever you want</div>
                    <textarea class="ques" name="question" required></textarea>
                    <textarea class="key" placeholder="Enter Key words using #" name="key" required></textarea>
                    <input type="submit" value="Post">
                    <input type="reset" value="Cancel">
                </form>
            </div>
            <hr><br>
            <div class="latest-question">
                <div class="head_1">Your Questions</div><br>
                {% if question_list|length == 0 %}
                    You didn't post any Questions yet. Post your first Question and keep going!
                {% endif %}
                {% if question_list %}
                    {% for question in question_list %}
                        <div class="question_">
                            <div class="user">{{ question.user.username }}{% if question.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ question.pub_date|timesince }} ago</span></div>
                            <div class="_question">{{ question.question_text}}</div>
                            {% for answer in question.answer_set.all|slice:":5" %}
                                <div class="answer_">
                                    <div class="user">{{ answer.user.username }}{% if answer.user.username == user.username %} (you){% endif %}<span class="pub-date">{{ answer.pub_date|timesince }} ago</span></div>
                                    <div class="answer">{{ answer.answer_text}}</div>
                                    <div class="edit">{% if answer.user.username == user.username %}
                                        <a href="{% url 'room:to_edit' answer.id %}">edit</a> | <a href="{% url 'room:delete_answer' answer.id%}">delete</a>
                                    {% endif %}</div>
                                <span class="like">{{ answer.votes }} votes <a href="{% url 'room:like' answer.id %}" class="like">| <i class="fas fa-fist-raised"></i></a></span>
                                <div></div>
                                </div>

                                {% empty %}
                                {% if question.user.username != user.username %}
                                <br>
                                <i><b>be the first to answer this question</b></i>
                                {% endif %}
                            {% endfor %}
                            <div class="new-answer"><br>
                                <form action="{% url 'room:update_answer' question.id %}" method="post">{% csrf_token %}
                                    <div class="head_2">Post your answer</div>
                                    <textarea class="post-ans" placeholder="Post your answer for this question" name="answer" required></textarea>
                                    <input type="submit" value="Post">
                                    <input type="reset" value="Cancel">
                                </form>
                            </div>
                        <div class="edit">You want to delete this Question?</div>
                        <a href="{% url 'room:delete_question' question.id %}">Delete</a>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="side-bar">
            <div class="profile">
                <div class="profile-pic"><i class="fas fa-user-circle"></i></div>
                <div class="profile-name">{{ user.get_full_name }}</div>
                <div class="profile-email">{{ user.email }}</div>
                <div class="profile-dis">Student at University of Kelaniya</div>
                <div class="profile-nav">
                    <nav><b>-- Your Posts --</b></nav>
                    <nav>> <a href="{% url 'room:question' %}">Questions</a></nav>
                    <nav>> <a href="{% url 'room:answer' %}">Answers&nbsp;&nbsp;</a></nav><br>
                    <nav>Settings | <a href="{% url 'login:logout' %}">{% csrf_token %}logout</a></nav><br>
                </div>

            </div>
            <p>The study room gives you a collaborative environment to learn. You can post your questions, and others can answer your questions as well as you also can answer other questions. If you want to improve this application or contribute to this application, you can fork from my github repository. <a href="https://github.com/josiahprathaban/studyROOM" target="_blank">https://github.com /josiahprathaban /studyROOM.</a> Make use of it. Have fun!</p>            <hr>Powered by<br>
            <hr>Powered by<br>
            <unknown>UNKNOWN</unknown><inc> Inc.</inc>
            <!--<img src="{% static 'room/unknown.svg' %}" width="180px">-->
        </div>
    </div>
    <a href="#top"><div class="up">^<br>up</div></a>
    <div class="footer">
        <span class="head_2">Contact us</span> |
        <a href="https://www.linkedin.com/in/josiah-prathaban/" target="_blank"><i class="fab fa-linkedin"></i></a>  |
        <a href="https://github.com/josiahprathaban" target="_blank"><i class="fab fa-github-square"></i></a>  |
        <a href="https://www.facebook.com/josiah.prathaban" target="_blank"><i class="fab fa-facebook-square"></i></a>  |
        <a href="https://www.blogger.com/profile/14730380695491700190" target="_blank"><i class="fab fa-blogger"></i></a>  |
        <i class="fab fa-whatsapp"></i> <span class="head_2">+94 76 6641 296</span>
    </div>
</body>
</html>